# Generated by Django 3.1.2 on 2022-04-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='favoritedBy',
        ),
    ]
