# Generated by Django 3.1.2 on 2022-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='favoritedBy',
            field=models.ManyToManyField(to='recipes.User'),
        ),
    ]
