# Generated by Django 3.1.2 on 2022-03-26 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='blurb',
            field=models.CharField(default='no blurb entered', max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficultyRating',
            field=models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servingSize',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
