# Generated by Django 3.1.2 on 2022-04-22 16:32

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='forks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspiredForks', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='profile_img/'),
        ),
    ]
