# Generated by Django 4.0.2 on 2022-04-18 02:15

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default="{% static 'recipes/default_chef.png' %}", storage=gdstorage.storage.GoogleDriveStorage(), upload_to='profile_img/'),
        ),
    ]
