# Generated by Django 3.1.2 on 2022-04-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_favoritedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='create', to='recipes.user'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favoritedBy',
            field=models.ManyToManyField(related_name='favorite', to='recipes.User'),
        ),
    ]
