# Generated by Django 3.1.2 on 2022-04-07 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220407_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='createdBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='create', to='recipes.profile'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='favoritedBy',
            field=models.ManyToManyField(related_name='favorites', to='recipes.Profile'),
        ),
    ]
