# Generated by Django 3.1.2 on 2022-04-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220401_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='favoritedBy',
            field=models.ManyToManyField(related_name='favorites', to='recipes.User'),
        ),
    ]
