# Generated by Django 4.0.2 on 2022-04-04 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('recipes', '0003_alter_recipe_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('cooking_experience', models.IntegerField()),
            ],
            options={
                'db_table': 'profile',
                'managed': False,
            },
        ),
    ]
