# Generated by Django 3.1.2 on 2022-04-08 14:44

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220407_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='null', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='profile_img/'),
        ),
    ]
