# Generated by Django 3.1.2 on 2022-04-08 21:30

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220408_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='profile_img/')),
                ('recipe', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recipes.profile')),
            ],
        ),
    ]
