# Generated by Django 3.1.2 on 2022-04-08 21:49

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220408_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='image',
            field=models.ImageField(default='', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='recipe_img/'),
        ),
    ]
